repo: 'grid-ception'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css-order-grid-main
  - css
  - img-flex
  - responsive-css
  - border-box
  - screenshots-al

html:
  - path: 'index.html'
    has:
      - 'h1'
      - 'h2'
      - 'p'
      - 'dl'
      - 'dl > dt'
      - 'dl > dd'
      - 'img[class~="img-flex"]'
      - 'time[datetime]'
    has_not:
      - 'br'
    search:
      - 'Moons of Mars'
      - 'Deimos'
      - 'Phobos'
      - 'Deimosian'
      - 'Phobian'
      - 'Asaph Hall'
      - 'August 17, 1877'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font-family', 'sans-serif']
